/**
 * Service unit / plist / WinSW generators (pure strings for tests + install).
 */
import path from "node:path";
import type { CliInvocation } from "./resolve-exec.js";
import { serviceStartArgs, shellQuote } from "./resolve-exec.js";
import { defaultConfigPath, defaultLogFilePath, CLI_NAME } from "../util/paths.js";

export const LAUNCHD_LABEL = "com.agent-connect.bridge";
export const SYSTEMD_UNIT_NAME = "agent-connect.service";
export const WINDOWS_SERVICE_ID = "agent-connect";
export const WINDOWS_TASK_NAME = "agent-connect";

export interface TemplateContext {
  inv: CliInvocation;
  /** HOME / USERPROFILE for the service user */
  home: string;
  configPath?: string;
  logFile?: string;
  /** Extra args after start --all */
  extraArgs?: string[];
}

function envHome(home: string): { HOME: string; USERPROFILE: string } {
  return { HOME: home, USERPROFILE: home };
}

/** systemd --user unit body */
export function renderSystemdUserUnit(ctx: TemplateContext): string {
  const { inv, home } = ctx;
  const logFile = ctx.logFile || defaultLogFilePath(path.join(home, ".agent-connect"));
  const configPath = ctx.configPath || defaultConfigPath(path.join(home, ".agent-connect"));
  const args = serviceStartArgs(inv, [
    "--config",
    configPath,
    "--log-file",
    logFile,
    ...(ctx.extraArgs || []),
  ]);
  const execStart = [inv.executable, ...args].map(shellQuote).join(" ");

  return `# Generated by agent-connect service install
# User unit: ~/.config/systemd/user/${SYSTEMD_UNIT_NAME}
[Unit]
Description=agent-connect — local IM ↔ coding-agent bridge
Documentation=https://github.com/RongleCat/agent-connect
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${execStart}
WorkingDirectory=${shellQuote(inv.workDir)}
Restart=on-failure
RestartSec=5
KillMode=mixed
TimeoutStopSec=20
Environment=HOME=${shellQuote(home)}
Environment=PATH=${shellQuote(process.env.PATH || "/usr/local/bin:/usr/bin:/bin")}

# Do not run as root; install as systemd --user

[Install]
WantedBy=default.target
`;
}

/** launchd LaunchAgent plist */
export function renderLaunchdPlist(ctx: TemplateContext): string {
  const { inv, home } = ctx;
  const logFile = ctx.logFile || defaultLogFilePath(path.join(home, ".agent-connect"));
  const configPath = ctx.configPath || defaultConfigPath(path.join(home, ".agent-connect"));
  const args = serviceStartArgs(inv, [
    "--config",
    configPath,
    "--log-file",
    logFile,
    ...(ctx.extraArgs || []),
  ]);
  const programArgs = [inv.executable, ...args]
    .map((a) => `    <string>${escapeXml(a)}</string>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by agent-connect service install -->
<!-- ~/Library/LaunchAgents/${LAUNCHD_LABEL}.plist -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
${programArgs}
  </array>
  <key>WorkingDirectory</key>
  <string>${escapeXml(inv.workDir)}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ProcessType</key>
  <string>Background</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>${escapeXml(home)}</string>
    <key>PATH</key>
    <string>${escapeXml(process.env.PATH || "/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin")}</string>
  </dict>
  <key>StandardOutPath</key>
  <string>${escapeXml(logFile)}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(logFile)}</string>
</dict>
</plist>
`;
}

/** WinSW XML (Windows Service wrapper) */
export function renderWinswXml(ctx: TemplateContext): string {
  const { inv, home } = ctx;
  const logDir = path.join(home, ".agent-connect", "logs");
  const configPath = ctx.configPath || defaultConfigPath(path.join(home, ".agent-connect"));
  const logFile = ctx.logFile || defaultLogFilePath(path.join(home, ".agent-connect"));
  const args = serviceStartArgs(inv, [
    "--config",
    configPath,
    "--log-file",
    logFile,
    ...(ctx.extraArgs || []),
  ]);
  const argumentsLine = args.map(escapeXml).join(" ");

  return `<service>
  <!-- Generated by agent-connect service install -->
  <!-- Pair with WinSW: rename WinSW.exe → agent-connect-service.exe next to this XML -->
  <id>${WINDOWS_SERVICE_ID}</id>
  <name>agent-connect</name>
  <description>agent-connect — local multi-project IM ↔ coding-agent bridge (Feishu × Grok)</description>
  <executable>${escapeXml(inv.executable)}</executable>
  <arguments>${argumentsLine}</arguments>
  <workingdirectory>${escapeXml(inv.workDir)}</workingdirectory>
  <env name="HOME" value="${escapeXml(home)}" />
  <env name="USERPROFILE" value="${escapeXml(home)}" />
  <env name="PATH" value="${escapeXml(process.env.PATH || "")}" />
  <logpath>${escapeXml(logDir)}</logpath>
  <log mode="roll-by-size">
    <sizeThreshold>10240</sizeThreshold>
    <keepFiles>8</keepFiles>
  </log>
  <onfailure action="restart" delay="10 sec"/>
  <resetfailure>1 hour</resetfailure>
  <stoptimeout>20 sec</stoptimeout>
  <startmode>Automatic</startmode>
</service>
`;
}

/** PowerShell snippet: register a logon Scheduled Task (no WinSW required) */
export function renderWindowsSchtasksPs1(ctx: TemplateContext): string {
  const { inv, home } = ctx;
  const configPath = ctx.configPath || defaultConfigPath(path.join(home, ".agent-connect"));
  const logFile = ctx.logFile || defaultLogFilePath(path.join(home, ".agent-connect"));
  const args = serviceStartArgs(inv, [
    "--config",
    configPath,
    "--log-file",
    logFile,
    ...(ctx.extraArgs || []),
  ]);
  const argString = args.map((a) => a.replace(/'/g, "''")).join(" ");

  return `# Generated by agent-connect service install (Scheduled Task fallback)
# Run in PowerShell (current user). Does NOT require WinSW.
$ErrorActionPreference = 'Stop'
$exe = '${inv.executable.replace(/'/g, "''")}'
$arg = '${argString}'
$wd  = '${inv.workDir.replace(/'/g, "''")}'
$action = New-ScheduledTaskAction -Execute $exe -Argument $arg -WorkingDirectory $wd
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$settings = New-ScheduledTaskSettingsSet \`
  -AllowStartIfOnBatteries \`
  -DontStopIfGoingOnBatteries \`
  -RestartCount 3 \`
  -RestartInterval (New-TimeSpan -Minutes 1) \`
  -ExecutionTimeLimit ([TimeSpan]::Zero)
Register-ScheduledTask -TaskName '${WINDOWS_TASK_NAME}' -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null
Write-Host "Registered Scheduled Task: ${WINDOWS_TASK_NAME}"
Write-Host "Start:  Start-ScheduledTask -TaskName '${WINDOWS_TASK_NAME}'"
Write-Host "Stop:   Stop-ScheduledTask  -TaskName '${WINDOWS_TASK_NAME}'  (or: agent-connect stop)"
`;
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function defaultLaunchAgentsPath(home = process.env.HOME || ""): string {
  return path.join(home, "Library", "LaunchAgents", `${LAUNCHD_LABEL}.plist`);
}

export function defaultSystemdUserUnitPath(home = process.env.HOME || ""): string {
  return path.join(home, ".config", "systemd", "user", SYSTEMD_UNIT_NAME);
}
