import type { SettingsEntry } from "../types";

/** Settings catalog entries — account section. */
export const ACCOUNT_ENTRIES: readonly SettingsEntry[] = [
  // ── account ──
  {
    id: "account.official",
    section: "account",
    tab: "official",
    anchorId: "settings-anchor-account-official",
    labelKey: "settings.tabOfficial",
    descKeys: [
      "settings.tabOfficialHint",
      "account.signedIn",
      "account.loginOauth",
      "account.loginDevice",
      "account.logout",
      "account.subscription",
      "account.quota",
      "account.profiles",
      "account.manageAccounts",
      "account.addAccount",
      "account.importChat",
    ],
    keywords: ["login", "oauth", "supergrok", "quota", "account"],
  },
  {
    id: "account.providers",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-account-providers",
    labelKey: "settings.tabProviders",
    descKeys: ["settings.tabProvidersHint"],
    keywords: [
      "provider",
      "relay",
      "custom api",
      "base url",
      "soft respawn",
      "live apply",
      "中转",
      "中轉",
      "提供商",
      "供應商",
    ],
  },
  {
    id: "account.officialApiKey",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-official-key",
    labelKey: "prov.officialApiKey",
    descKeys: ["prov.officialVoiceHint", "prov.officialDesc"],
    keywords: [
      "api key",
      "xai",
      "official key",
      "voice",
      "speech",
      "stt",
      "dictation",
      "语音",
      "語音",
      "听写",
    ],
  },
  {
    id: "account.extras",
    section: "account",
    tab: "extras",
    anchorId: "settings-anchor-account-extras",
    labelKey: "settings.tabExtras",
    descKeys: ["settings.tabExtrasHint"],
    keywords: [
      "extras",
      "拓展",
      "official tools",
      "inject",
      "official-aux",
      "官方工具",
    ],
  },
  {
    id: "account.officialAuxInject",
    section: "account",
    tab: "extras",
    anchorId: "settings-anchor-official-aux-inject",
    labelKey: "prov.officialAuxInject",
    descKeys: [
      "prov.officialAuxInjectDesc",
      "prov.officialAuxInjectDisabled",
      "prov.officialAuxWithUserMcp",
      "prov.officialAuxWithUserMcpDesc",
    ],
    keywords: [
      "official aux",
      "inject tools",
      "x_keyword_search",
      "web_search",
      "vision",
      "official-aux",
      "官方工具",
      "注入",
      "x搜索",
      "imagine",
      "image_gen",
      "画图",
      "custom only",
      "第三方",
      "MCP",
      "拓展",
    ],
  },
];
