import type { SettingsEntry } from "../types";

/** Settings catalog entries — extensions section. */
export const EXTENSIONS_ENTRIES: readonly SettingsEntry[] = [
  // ── extensions ──
  {
    id: "ext.plugins",
    section: "extensions",
    tab: "plugins",
    anchorId: "settings-anchor-ext-plugins",
    labelKey: "ext.plugins.title",
    descKeys: [
      "ext.lead",
      "ext.plugins.installLabel",
      "ext.plugins.recommendedTitle",
      "ext.plugins.installableTitle",
    ],
    keywords: ["plugin", "plugins", "extensions", "chatcut", "codex"],
  },
  {
    id: "ext.plugins.recommended",
    section: "extensions",
    tab: "plugins",
    anchorId: "settings-anchor-ext-plugins-recommended",
    labelKey: "ext.plugins.recommendedTitle",
    descKeys: ["ext.plugins.recommended.chatcutDesc"],
    keywords: ["chatcut", "codex", "recommended", "推荐", "推薦"],
  },
  {
    id: "ext.skills",
    section: "extensions",
    tab: "skills",
    anchorId: "settings-anchor-ext-skills",
    labelKey: "ext.skills.title",
    descKeys: ["ext.skills.edit", "ext.skills.editDisabledNote"],
    keywords: [
      "skill",
      "skills",
      "slash",
      "SKILL.md",
      "edit skill",
      "技能",
      "编辑技能",
    ],
  },
  {
    id: "ext.mcp",
    section: "extensions",
    tab: "mcp",
    anchorId: "settings-anchor-ext-mcp",
    labelKey: "ext.mcp.title",
    descKeys: [
      "ext.mcp.doctor",
      "ext.mcp.add",
      "mcpModal.oauth.authorize",
      "ext.mcp.auth.howToRefresh",
    ],
    keywords: [
      "mcp",
      "model context protocol",
      "server",
      "oauth",
      "authorize",
      "auth",
      "token",
      "credentials",
      "mcp doctor",
      "授权",
      "認證",
      "oauth 授权",
    ],
  },
  {
    id: "ext.agents",
    section: "extensions",
    tab: "agents",
    anchorId: "settings-anchor-ext-agents",
    labelKey: "ext.agents.title",
    descKeys: ["ext.agents.desc", "ext.agents.new"],
    keywords: [
      "agents",
      "agent definition",
      "persona",
      "scaffold",
      "new agent",
      "代理",
      "新建代理",
    ],
  },
  {
    id: "ext.hooks",
    section: "extensions",
    tab: "hooks",
    anchorId: "settings-anchor-ext-hooks",
    labelKey: "ext.hooks.title",
    keywords: ["hooks", "hook"],
  },
  {
    /** Legacy id kept for search; lands on plugins installable catalog (no market tab). */
    id: "ext.market",
    section: "extensions",
    tab: "plugins",
    anchorId: "settings-anchor-ext-plugins-catalog",
    labelKey: "ext.plugins.installableTitle",
    descKeys: ["ext.market.title", "ext.plugins.installableLead"],
    keywords: [
      "marketplace",
      "market",
      "install plugin",
      "市场",
      "市場",
      "市集",
      "openai",
      "openai/plugins",
      "catalog",
    ],
  },
];
