import type { SettingsEntry } from "../types";

/** Settings catalog entries — general section. */
export const GENERAL_ENTRIES: readonly SettingsEntry[] = [
  // ── general / composer ──
  {
    id: "general.prefsScope",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-prefsScope",
    labelKey: "settings.prefsScope",
    descKeys: [
      "settings.prefsScopeDesc",
      "settings.prefsScope.global",
      "settings.prefsScope.project",
      "settings.prefsScope.session",
      "settings.section.composer",
    ],
    keywords: ["composer", "prefs", "scope"],
  },
  {
    id: "general.availableModels",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-availableModels",
    labelKey: "settings.availableModels",
    descKeys: ["settings.availableModelsDesc"],
    keywords: ["models", "model list"],
  },
  {
    id: "general.composerMinRows",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerMinRows",
    labelKey: "settings.composerMinRows",
    descKeys: [
      "settings.composerMinRowsDesc",
      "settings.composerMinRows.2",
      "settings.composerMinRows.3",
      "settings.composerMinRows.5",
      "settings.composerMinRows.8",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "height",
      "min height",
      "minimum height",
      "rows",
      "input size",
      "textarea",
      "输入框高度",
      "輸入框高度",
      "最小高度",
      "行数",
      "行數",
    ],
  },
  {
    id: "general.composerSendKey",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerSendKey",
    labelKey: "settings.composerSendKey",
    descKeys: [
      "settings.composerSendKeyDesc",
      "settings.composerSendKey.enter",
      "settings.composerSendKey.modEnter",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "send",
      "enter",
      "mod-enter",
      "cmd enter",
      "ctrl enter",
      "newline",
      "keyboard",
    ],
  },
  {
    id: "general.composerSpellcheck",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerSpellcheck",
    labelKey: "settings.composerSpellcheck",
    descKeys: [
      "settings.composerSpellcheckDesc",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "spellcheck",
      "spell check",
      "spelling",
      "typo",
      "autocorrect",
    ],
  },
  {
    id: "general.composerDraftStats",
    section: "general",
    tab: "composer",
    anchorId: "settings-anchor-composerDraftStats",
    labelKey: "settings.composerDraftStats",
    descKeys: [
      "settings.composerDraftStatsDesc",
      "settings.section.composer",
    ],
    keywords: [
      "composer",
      "draft",
      "stats",
      "character",
      "char count",
      "word count",
      "words",
      "length",
    ],
  },
  // ── general / permissions ──
  {
    id: "general.permissionPolicy",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-permissionPolicy",
    labelKey: "settings.permissionDeep",
    descKeys: [
      "settings.permissionDeepDesc",
      "settings.permissionCliMode",
      "settings.section.permissions",
      "policy.ask",
      "policy.accept_edits",
      "policy.allow_for_session",
      "policy.auto",
      "policy.dont_ask",
      "policy.always_approve",
    ],
    keywords: [
      "permission",
      "yolo",
      "always approve",
      "policy",
      "permission-mode",
      "acceptEdits",
      "bypassPermissions",
      "dontAsk",
    ],
  },
  {
    id: "general.cliPermissionMode",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-cliPermissionModeAdvanced",
    labelKey: "settings.permissionCliAdvanced",
    descKeys: [
      "settings.permissionCliAdvancedDesc",
      "settings.permissionCliAdvancedHint",
      "cliPermission.default",
      "cliPermission.acceptEdits",
      "cliPermission.auto",
      "cliPermission.dontAsk",
      "cliPermission.bypassPermissions",
      "cliPermission.plan",
    ],
    keywords: [
      "permission-mode",
      "cli",
      "default",
      "acceptEdits",
      "auto",
      "dontAsk",
      "bypassPermissions",
      "plan",
      "yolo",
    ],
  },
  {
    id: "general.sandbox",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-sandbox",
    labelKey: "settings.sandboxProfile",
    descKeys: [
      "settings.sandboxProfileDesc",
      "settings.sandbox.off",
      "settings.sandbox.off.help",
      "settings.sandbox.workspace",
      "settings.sandbox.workspace.help",
      "settings.sandbox.readOnly",
      "settings.sandbox.readOnly.help",
      "settings.sandbox.strict",
      "settings.sandbox.strict.help",
      "settings.sandbox.devbox",
      "settings.sandbox.devbox.help",
      "settings.sandbox.softFail.cliMissing",
      "settings.sandbox.softFail.cliUnsupported",
      "settings.sandbox.softFail.platform",
      "settings.sandbox.networkLinuxOnly",
      "settings.sandbox.recommendedNote",
      "settings.section.permissions",
    ],
    keywords: [
      "sandbox",
      "landlock",
      "seatbelt",
      "isolation",
      "devbox",
      "workspace sandbox",
      "read-only",
      "strict sandbox",
      "soft-fail",
      "GROK_SANDBOX",
      "--sandbox",
      "沙箱",
      "隔离",
      "沙箱設定",
      "沙箱配置",
    ],
  },
  {
    id: "general.permissionRules",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-permissionRules",
    labelKey: "settings.section.permissions",
    keywords: ["rules", "permission rules"],
  },
  {
    id: "general.permissionTimeout",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-permissionTimeout",
    labelKey: "settings.permissionTimeout",
    descKeys: [
      "settings.permissionTimeoutDesc",
      "settings.permissionTimeout.off",
      "settings.section.permissions",
    ],
    keywords: [
      "auto-deny",
      "timeout",
      "permission timeout",
      "auto deny",
      "自动拒绝",
      "超时",
    ],
  },
  {
    id: "general.askUserTimeout",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-askUserTimeout",
    labelKey: "settings.askUserTimeout",
    descKeys: [
      "settings.askUserTimeoutDesc",
      "settings.askUserTimeout.off",
      "settings.section.permissions",
      "askUser.title",
    ],
    keywords: [
      "ask user",
      "ask question",
      "questionnaire",
      "timeout",
      "auto-dismiss",
      "auto cancel",
      "ask_user_question",
      "提问超时",
      "问卷",
      "自动忽略",
      "超时",
    ],
  },
  {
    id: "general.askUserDemo",
    section: "general",
    tab: "permissions",
    anchorId: "settings-anchor-askUserDemo",
    labelKey: "settings.askDemo.title",
    descKeys: [
      "settings.askDemo.desc",
      "settings.askDemo.honesty",
      "settings.askDemo.step.policyAsk",
      "settings.askDemo.step.notYolo",
      "settings.askDemo.step.askUserEnabled",
      "settings.askDemo.step.samplePrompt",
      "settings.askDemo.apply",
      "settings.askDemo.copyPrompt",
      "settings.askDemo.preview",
      "settings.section.permissions",
      "askUser.title",
      "settings.noAskUser",
    ],
    keywords: [
      "ask user",
      "ask-user",
      "demo path",
      "demo checklist",
      "questionnaire preview",
      "sample prompt",
      "yolo comparison",
      "ask vs yolo",
      "ask_user_question",
      "no-ask-user",
      "演示路径",
      "示范路径",
      "问卷预览",
      "示例提示",
      "示例提示词",
    ],
  },
  // ── general / agent ──
  {
    id: "general.maxAgentTurns",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-maxAgentTurns",
    labelKey: "settings.maxAgentTurns",
    descKeys: ["settings.maxAgentTurnsDesc", "settings.section.agent"],
    keywords: ["max turns", "turns"],
  },
  {
    id: "general.backgroundWaitPolicy",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-backgroundWait",
    labelKey: "settings.backgroundWaitPolicy",
    descKeys: [
      "settings.backgroundWaitPolicyDesc",
      "settings.backgroundWait.wait",
      "settings.backgroundWait.noWait",
      "settings.backgroundWait.timeout",
      "settings.backgroundWaitTimeout",
      "settings.backgroundWaitTimeoutDesc",
      "settings.section.agent",
    ],
    keywords: [
      "background wait",
      "no-wait-for-background",
      "background-wait-timeout",
      "headless wait",
      "background tasks",
      "wait for background",
      "后台等待",
      "背景等待",
      "不等待后台",
    ],
  },
  {
    id: "general.preferredAgent",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-preferredAgent",
    labelKey: "settings.preferredAgent",
    descKeys: ["settings.preferredAgentDesc"],
    keywords: ["preferred agent", "agent definition"],
  },
  {
    id: "general.agentsPersonas",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-agentsPersonas",
    labelKey: "settings.agentsPersonas.title",
    descKeys: [
      "settings.agentsPersonas.desc",
      "settings.agentsPersonas.tab.agents",
      "settings.agentsPersonas.tab.personas",
      "settings.agentsPersonas.refresh",
    ],
    keywords: [
      "agents",
      "personas",
      "agents and personas",
      "config-agents",
      "agent definition",
      "persona",
      "preferred agent",
      "代理",
      "人格",
      "角色",
      "agents 控制台",
      "personas 目錄",
    ],
  },
  {
    id: "general.agentProfilePath",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-agentProfilePath",
    labelKey: "settings.agentProfilePath",
    descKeys: [
      "settings.agentProfilePathDesc",
      "settings.agentProfilePathBrowse",
      "settings.agentProfilePathClear",
    ],
    keywords: [
      "agent profile",
      "agent-profile",
      "profile path",
      "agent profile path",
      "profile 文件",
      "profile 路徑",
      "agent profile 路径",
    ],
  },
  {
    id: "general.configTomlView",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-configTomlView",
    labelKey: "settings.configTomlView",
    descKeys: [
      "settings.configTomlViewDesc",
      "settings.configTomlView.open",
      "settings.configTomlView.redactNote",
      "settings.configTomlView.sharedWarning",
    ],
    keywords: [
      "config.toml",
      "agent config",
      "view config",
      "config view",
      "redacted config",
      "agent-home config",
      "配置文件",
      "查看配置",
      "config 檢視",
    ],
  },
  {
    id: "general.agentsJson",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-agentsJson",
    labelKey: "settings.agentsJson",
    descKeys: [
      "settings.agentsJsonDesc",
      "settings.agentsJsonPlaceholder",
      "settings.agentsJsonInvalid",
      "settings.agentsJsonApply",
      "settings.agentsJsonClear",
    ],
    keywords: [
      "agents json",
      "--agents",
      "inline agents",
      "subagent definitions",
      "agents JSON",
      "内联 agents",
      "內聯 agents",
      "子代理 JSON",
    ],
  },
  {
    id: "general.experimentalMemory",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-experimentalMemory",
    labelKey: "settings.experimentalMemory",
    descKeys: ["settings.experimentalMemoryDesc"],
    keywords: ["memory"],
  },
  {
    id: "general.compactionMode",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-compactionMode",
    labelKey: "settings.compactionMode",
    descKeys: [
      "settings.compactionModeDesc",
      "settings.compactionMode.summary",
      "settings.compactionMode.transcript",
      "settings.compactionMode.segments",
      "settings.compactionMode.summary.help",
      "settings.compactionMode.transcript.help",
      "settings.compactionMode.segments.help",
      "settings.compactionApply.note",
      "settings.compactionApply.softRespawn",
      "settings.compactionApply.nextSpawn",
      "settings.compactionApply.unsupported",
    ],
    keywords: [
      "compaction",
      "compaction mode",
      "compact mode",
      "--compaction-mode",
      "GROK_COMPACTION_MODE",
      "summary",
      "transcript",
      "segments",
      "soft-respawn",
      "soft respawn",
      "next spawn",
      "压缩模式",
      "壓縮模式",
    ],
  },
  {
    id: "general.compactionDetail",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-compactionDetail",
    labelKey: "settings.compactionDetail",
    descKeys: [
      "settings.compactionDetailDesc",
      "settings.compactionDetail.none",
      "settings.compactionDetail.minimal",
      "settings.compactionDetail.balanced",
      "settings.compactionDetail.verbose",
      "settings.compactionDetail.help",
      "settings.compactionApply.note",
    ],
    keywords: [
      "compaction detail",
      "segments detail",
      "--compaction-detail",
      "GROK_COMPACTION_DETAIL",
      "minimal",
      "balanced",
      "verbose",
      "soft-respawn",
      "分段细节",
      "分段細節",
    ],
  },
  {
    id: "general.twoPassCompaction",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-twoPassCompaction",
    labelKey: "settings.twoPassCompaction",
    descKeys: ["settings.twoPassCompactionDesc"],
    keywords: [
      "two pass compaction",
      "two-pass",
      "prefire",
      "two_pass_compaction_enabled",
      "GROK_TWO_PASS_COMPACTION",
      "hierarchical compact",
      "双遍压缩",
      "雙遍壓縮",
      "两遍压缩",
      "兩遍壓縮",
    ],
  },
  {
    id: "general.memoryBrowser",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-memoryBrowser",
    labelKey: "settings.memoryOps",
    descKeys: [
      "settings.memoryOpsDesc",
      "settings.memoryBrowser",
      "settings.memoryBrowserDesc",
      "settings.memoryBrowser.off",
      "settings.memoryBrowser.filterEmpty",
      "settings.memoryBrowser.filterEmptyHintKind",
      "settings.memoryBrowser.searchEmptyHint",
      "settings.memoryBrowser.searchEmptyHintKeyword",
      "settings.memoryBrowser.searchEmptyHintHybridUnavailable",
      "settings.memoryBrowser.emptyHint",
      "settings.clearWorkspaceMemory",
      "settings.memoryBrowser.searchMode.appKeyword",
      "settings.memoryBrowser.searchMode.hybridUnavailable",
      "settings.memoryBrowser.searchKind.hybridUnavailable",
      "settings.memoryBrowser.embedUnsetHint",
      "settings.memoryBrowser.hybridUnavailableHint",
      "settings.memoryOps.mode.appKeyword",
      "settings.memoryOps.mode.hybridUnavailable",
      "settings.memoryOps.mode.memoryOff",
      "settings.memoryOps.hybridUnavailableHint",
      "settings.memoryOps.clear.workspace",
      "settings.memoryOps.clear.session",
      "settings.memoryOps.clear.all",
      "settings.memoryOps.dream",
      "settings.memoryOps.watcher",
      "settings.memoryOps.presenceNote",
    ],
    keywords: [
      "memory browser",
      "memory ops",
      "memory operations",
      "MEMORY.md",
      "workspace memory",
      "browse memory",
      "memory filter",
      "memory search",
      "hybrid search",
      "hybrid unavailable",
      "content search",
      "keyword only",
      "no embeddings",
      "reveal",
      "clear memory",
      "clear all memory",
      "dream",
      "watcher",
      "记忆",
      "記憶",
      "memory files",
      "记忆搜索",
      "記憶搜尋",
      "混合检索",
      "混合檢索",
      "embedding",
      "keyword search",
      "kind filter",
      "记忆操作中心",
      "記憶操作中心",
    ],
  },
  {
    id: "general.memoryEmbed",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-memoryEmbed",
    labelKey: "settings.memoryEmbed",
    descKeys: [
      "settings.memoryEmbedDesc",
      "settings.memoryEmbed.model",
      "settings.memoryEmbed.mmr",
      "settings.memoryEmbed.dream",
      "settings.memoryEmbed.embeddingEmpty",
      "settings.memoryEmbed.sharedWarning",
    ],
    keywords: [
      "memory embedding",
      "embedding model",
      "memory_embedding_model",
      "memory search",
      "mmr",
      "memory_mmr",
      "dream",
      "temporal decay",
      "vector search",
      "hybrid search",
      "memory.embed",
      "记忆 embedding",
      "記憶 embedding",
      "向量",
      "0.2.117",
    ],
  },
  {
    id: "general.codebaseIndexing",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-codebaseIndexing",
    labelKey: "settings.codebaseIndexing",
    descKeys: [
      "settings.codebaseIndexingDesc",
      "settings.codebaseIndexing.enable",
      "settings.codebaseIndexing.enableDesc",
      "settings.codebaseIndexing.noEmbeddings",
      "settings.codebaseIndexing.sharedWarning",
      "settings.codebaseIndexing.unsetDefaultHint",
      "settings.codeGraph.appSearchRemainsKeyword",
      "settings.codeGraph.mode.graphUnavailable",
    ],
    keywords: [
      "codebase indexing",
      "codebase_indexing",
      "code graph",
      "code-nav",
      "features.codebase_indexing",
      "[features] codebase_indexing",
      "index",
      "代码库索引",
      "程式碼庫索引",
      "代码图",
      "程式碼圖",
      "keyword vs graph",
      "not embeddings",
      "0.2.117",
    ],
  },
  {
    id: "general.lspTools",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-lspTools",
    labelKey: "settings.lspTools",
    descKeys: [
      "settings.lspToolsDesc",
      "settings.lspTools.enable",
      "settings.lspTools.enableDesc",
      "settings.lspTools.sharedWarning",
      "settings.lspTools.unsetDefaultHint",
      "settings.lspTools.empty.noDiagnostics",
      "settings.lspTools.banner.noAppLsp",
      "settings.lspTools.banner.agentToolsOnly",
      "settings.lspTools.banner.softRespawn",
    ],
    keywords: [
      "lsp",
      "lsp tools",
      "lsp_tools",
      "[features] lsp_tools",
      "features.lsp_tools",
      "language server",
      "language-server",
      "diagnostics",
      "no diagnostics",
      "agent tools",
      "soft-respawn",
      "config.toml",
      "LSP 工具",
      "语言服务器",
      "語言伺服器",
      "诊断",
      "診斷",
      "0.2.117",
    ],
  },
  {
    id: "general.codebaseSearch",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-codebaseSearch",
    labelKey: "settings.codebaseSearch",
    descKeys: [
      "settings.codebaseSearchDesc",
      "settings.codebaseSearch.noEmbeddings",
      "settings.codebaseSearch.idleHint",
      "settings.codebaseSearch.mode.all",
      "settings.codebaseSearch.mode.name",
      "settings.codebaseSearch.mode.content",
      "settings.codeGraph.chip.appKeyword",
      "settings.codeGraph.chip.graphUnavailable",
    ],
    keywords: [
      "codebase search",
      "project search",
      "file search",
      "content search",
      "rg",
      "ripgrep",
      "keyword search",
      "find in files",
      "code graph",
      "keyword vs graph",
      "代码库搜索",
      "專案搜尋",
      "文件搜索",
      "內容搜尋",
      "代码图",
      "程式碼圖",
      "not embeddings",
    ],
  },
  {
    id: "general.codeGraph",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-codeGraph",
    labelKey: "settings.codeGraph",
    descKeys: [
      "settings.codeGraphDesc",
      "settings.codeGraph.appSearchRemainsKeyword",
      "settings.codeGraph.mode.graphUnavailable",
      "settings.codeGraph.rebuild.unavailableNote",
    ],
    keywords: [
      "code graph",
      "codegraph",
      "keyword vs graph",
      "graph search",
      "graph unavailable",
      "codebase indexing",
      "project search",
      "代码图",
      "程式碼圖",
      "关键词",
      "關鍵字",
      "not embeddings",
      "rebuild",
    ],
  },
  {
    id: "general.subagents",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-subagents",
    labelKey: "settings.subagentsEnabled",
    descKeys: ["settings.subagentsEnabledDesc"],
    keywords: ["subagents", "sub-agent"],
  },
  {
    id: "general.subagentWorktreeSnapshot",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-subagentWtSnap",
    labelKey: "settings.subagentWorktreeSnapshot",
    descKeys: [
      "settings.subagentWorktreeSnapshotDesc",
      "tasks.subagentWtSnapNote",
    ],
    keywords: [
      "subagent worktree snapshot",
      "subagent_worktree_snapshot_enabled",
      "GROK_SUBAGENT_WORKTREE_SNAPSHOT",
      "worktree snapshot",
      "subagent snapshot",
      "子代理 worktree 快照",
      "子代理工作樹快照",
      "快照",
    ],
  },
  {
    id: "general.autoWake",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-autoWake",
    labelKey: "settings.autoWake",
    descKeys: ["settings.autoWakeDesc"],
    keywords: [
      "auto wake",
      "auto-wake",
      "auto_wake_enabled",
      "background task wake",
      "synthetic turn",
      "task completed",
      "monitor wake",
      "自动唤醒",
      "自動喚醒",
      "后台任务",
      "背景任務",
    ],
  },
  {
    id: "general.configTomlEdit",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-configTomlEdit",
    labelKey: "settings.configTomlEdit",
    descKeys: [
      "settings.configTomlEditDesc",
      "settings.configTomlEdit.sharedWarning",
      "settings.configTomlEdit.redactNote",
    ],
    keywords: [
      "config.toml",
      "agent-home",
      "config edit",
      "section edit",
      "permission_mode",
      "yolo",
      "subagents",
      "memory",
      "workflows",
      "workflows_enabled",
      "auto_wake",
      "auto_wake_enabled",
      "two_pass_compaction",
      "lsp_tools",
      "codebase_indexing",
      "remote_fetch",
      "features",
      "GROK_HOME",
      "配置编辑",
      "配置編輯",
      "agent-home 配置",
      "工作流",
      "自动唤醒",
      "自動喚醒",
      "两遍压缩",
      "兩遍壓縮",
    ],
  },
  {
    id: "general.plan",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-planEnabled",
    labelKey: "settings.planEnabled",
    descKeys: ["settings.planEnabledDesc"],
    keywords: ["plan mode"],
  },
  {
    id: "general.todoGate",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-todoGate",
    labelKey: "settings.todoGate",
    descKeys: [
      "settings.todoGateDesc",
      "settings.todoGate.softRespawnNote",
      "settings.todoGate.activity.na",
      "settings.todoGateMaxFires",
      "settings.todoGateMaxFiresDesc",
      "settings.todoGateMaxFires.effective",
      "settings.todoGateMaxFires.independent",
      "settings.todoGateMaxFires.shared",
      "settings.todoGateMaxFires.inactive",
    ],
    keywords: [
      "todo gate",
      "todogate",
      "--todo-gate",
      "todo_gate_enabled",
      "todo_gate_max_fires_per_prompt",
      "max fires",
      "pending todos",
      "turn-end",
      "TodoGate",
      "soft-respawn",
      "gate activity",
      "待办门控",
      "待辦門控",
      "todo 门控",
      "最大触发",
      "最大觸發",
    ],
  },
  {
    id: "general.disableWebSearch",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-disableWebSearch",
    labelKey: "settings.disableWebSearch",
    descKeys: ["settings.disableWebSearchDesc"],
    keywords: ["web search"],
  },
  {
    id: "general.noAskUser",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-noAskUser",
    labelKey: "settings.noAskUser",
    descKeys: ["settings.noAskUserDesc"],
    keywords: [
      "no ask user",
      "no-ask-user",
      "ask_user_question",
      "ask user",
      "questionnaire",
      "0.2.117",
      "不问用户",
      "不问用户问题",
      "禁用提问",
    ],
  },
  {
    id: "general.allowedTools",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-allowedTools",
    labelKey: "settings.allowedTools",
    descKeys: [
      "settings.allowedToolsDesc",
      "settings.allowedTools.bothSet",
    ],
    keywords: [
      "allowed tools",
      "allowlist",
      "tools allow",
      "--tools",
      "web_search",
      "run_terminal_command",
      "tool allow",
    ],
  },
  {
    id: "general.disallowedTools",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-disallowedTools",
    labelKey: "settings.disallowedTools",
    descKeys: [
      "settings.disallowedToolsDesc",
      "settings.disallowedTools.webCovered",
      "settings.allowedTools.bothSet",
    ],
    keywords: [
      "disallowed tools",
      "deny tools",
      "web_search",
      "web_fetch",
      "run_terminal_command",
      "tool deny",
    ],
  },
  {
    id: "general.useLeader",
    section: "general",
    tab: "agent",
    anchorId: "settings-anchor-useLeader",
    labelKey: "settings.useLeader",
    descKeys: ["settings.useLeaderDesc"],
    keywords: ["leader"],
  },
  // ── general / app ──
  {
    id: "general.language",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-language",
    labelKey: "settings.language",
    descKeys: ["settings.languageDesc", "settings.section.general"],
    keywords: [
      "language",
      "locale",
      "中文",
      "english",
      "system",
      "跟随系统",
      "跟隨系統",
    ],
  },
  {
    id: "general.sessionDataMode",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-sessionDataMode",
    labelKey: "settings.sessionDataMode",
    descKeys: [
      "settings.sessionDataModeDesc",
      "settings.modeIndependent",
      "settings.modeShared",
      "settings.sessionModeHelp",
      "settings.sessionDataMode.status",
      "settings.sessionDataMode.banner.sharedWithCli",
      "settings.sessionDataMode.banner.noRewriteSecrets",
      "settings.sessionDataMode.banner.conflictPossible",
      "settings.sessionDataMode.risk.noSilentMerge",
      "settings.cliSessions",
    ],
    keywords: [
      "session data",
      "shared",
      "independent",
      "cli sessions",
      "agent-home",
      "GROK_HOME",
      "~/.grok",
      "merge",
      "recycle",
      "no silent merge",
      "会话数据",
      "共享",
      "独立",
    ],
  },
  {
    id: "general.cliSessions",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-cliSessions",
    labelKey: "settings.cliSessions",
    descKeys: [
      "settings.cliSessionsDesc",
      "settings.cliSessionsIndependentNote",
      "settings.cliSessionsImportOpen",
      "settings.cliSessionsDelete",
      "settings.cliSessionsDeleteUnlinked",
      "settings.cliSessionsFilterPlaceholder",
      "settings.cliSessionsSearchViaCli",
      "settings.cliSessionsEmptyCliMissing",
      "settings.cliSessions.clearFilters",
      "settings.cliSessions.filterLinked",
      "settings.cliSessions.filterUnlinked",
      "settings.cliSessions.err.cli_missing",
    ],
    keywords: [
      "cli sessions",
      "import session",
      "agent session id",
      "resume",
      "delete session",
      "search sessions",
      "first prompt",
      "linked",
      "unlinked",
      "clear filters",
      "cli missing",
      "CLI 会话",
      "导入会话",
      "删除会话",
      "搜索会话",
      "首条提示",
      "已关联",
      "未关联",
      "清除筛选",
    ],
  },
  {
    id: "general.voiceHotkeyEnabled",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceHotkeyEnabled",
    labelKey: "settings.voiceHotkeyEnabled",
    descKeys: ["settings.voiceHotkeyEnabledDesc", "settings.section.voice"],
    keywords: [
      "voice",
      "hotkey",
      "shortcut",
      "live voice",
      "keyboard",
      "语音",
      "快捷键",
      "实时语音",
    ],
  },
  {
    id: "general.voiceId",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceId",
    labelKey: "settings.voiceId",
    descKeys: ["settings.voiceIdDesc", "settings.section.voice"],
    keywords: ["voice", "speaker", "tts", "语音", "音色"],
  },
  {
    id: "general.voiceDictationAutoSend",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceDictationAutoSend",
    labelKey: "settings.voiceDictationAutoSend",
    descKeys: ["settings.voiceDictationAutoSendDesc"],
    keywords: ["dictation", "auto send", "听写", "语音输入"],
  },
  {
    id: "general.voiceKeepAgentsOnEnd",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-voiceKeepAgentsOnEnd",
    labelKey: "settings.voiceKeepAgentsOnEnd",
    descKeys: ["settings.voiceKeepAgentsOnEndDesc"],
    keywords: ["voice", "keep agents", "语音", "保留"],
  },
  {
    id: "general.keychain",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-keychain",
    labelKey: "settings.storeApiKeysInKeychain",
    descKeys: ["settings.storeApiKeysInKeychainDesc"],
    keywords: ["keychain", "api key", "secrets"],
  },
  {
    id: "general.clearMemory",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-clearMemory",
    labelKey: "settings.clearWorkspaceMemory",
    descKeys: ["settings.clearWorkspaceMemoryDesc"],
    keywords: ["clear memory", "workspace memory"],
  },
  {
    id: "general.reopenLastSession",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-reopenLastSession",
    labelKey: "settings.reopenLastSession",
    descKeys: ["settings.reopenLastSessionDesc"],
    keywords: ["reopen", "restore session"],
  },
  {
    id: "general.closeToTray",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-closeToTray",
    labelKey: "settings.closeToTray",
    descKeys: ["settings.closeToTrayDesc"],
    keywords: ["tray", "close", "minimize", "托盘", "系統匣", "关闭"],
  },
  {
    id: "general.keepTrayForSchedules",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-keepTrayForSchedules",
    labelKey: "settings.keepTrayForSchedules",
    descKeys: ["settings.keepTrayForSchedulesDesc"],
    keywords: [
      "tray",
      "schedules",
      "automations",
      "background",
      "keep",
      "scheduled",
      "托盘",
      "已安排",
      "调度",
      "系统匣",
      "排程",
    ],
  },
  {
    id: "general.trayBusyBadge",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-trayBusyBadge",
    labelKey: "settings.trayBusyBadge",
    descKeys: [
      "settings.trayBusyBadgeDesc",
      "settings.trayBusyBadge.status.off",
      "settings.trayBusyBadge.status.idle",
      "settings.trayBusyBadge.status.busy",
      "settings.trayBusyBadge.status.capped",
    ],
    keywords: [
      "badge",
      "dock",
      "tray",
      "busy",
      "count",
      "角标",
      "徽章",
      "托盘",
      "忙碌",
      "系統匣",
      "notify",
      "notification",
    ],
  },
  {
    id: "general.notifyHonesty",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyHonesty",
    labelKey: "settings.notify.honesty.title",
    descKeys: [
      "settings.notify.honesty.desc",
      "settings.notify.honesty.ok",
      "settings.notify.honesty.osDenied",
      "settings.notify.honesty.osDefault",
      "settings.notify.honesty.osUnsupported",
      "settings.notify.honesty.prefsOff",
      "settings.notify.honesty.quietHours",
    ],
    keywords: [
      "notification",
      "desktop",
      "permission",
      "os",
      "quiet hours",
      "dnd",
      "notify",
      "桌面通知",
      "系统权限",
      "免打扰",
      "通知權限",
    ],
  },
  {
    id: "general.launchAtLogin",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-launchAtLogin",
    labelKey: "settings.launchAtLogin",
    descKeys: ["settings.launchAtLoginDesc"],
    keywords: [
      "launch",
      "login",
      "startup",
      "autostart",
      "boot",
      "automation",
      "scheduled",
      "schedule",
      "daemon",
      "background",
      "开机",
      "登录",
      "啟動",
      "登入",
      "自动化",
      "已安排",
      "排程",
      "后台",
      "背景",
    ],
  },
  {
    id: "general.windowAlwaysOnTop",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-windowAlwaysOnTop",
    labelKey: "settings.windowAlwaysOnTop",
    descKeys: ["settings.windowAlwaysOnTopDesc"],
    keywords: [
      "always on top",
      "pin",
      "float",
      "stay on top",
      "置顶",
      "置頂",
      "窗口",
      "視窗",
    ],
  },
  {
    id: "general.notifyOnTurnDone",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyOnTurnDone",
    labelKey: "settings.notifyOnTurnDone",
    descKeys: ["settings.notifyOnTurnDoneDesc"],
    keywords: [
      "notification",
      "desktop",
      "alert",
      "turn done",
      "notify",
      "桌面通知",
      "完成通知",
    ],
  },
  {
    id: "general.notifyOnPermission",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyOnPermission",
    labelKey: "settings.notifyOnPermission",
    descKeys: ["settings.notifyOnPermissionDesc"],
    keywords: [
      "notification",
      "desktop",
      "alert",
      "permission",
      "notify",
      "桌面通知",
      "授权通知",
    ],
  },
  {
    id: "general.notifySound",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifySound",
    labelKey: "settings.notifySound",
    descKeys: ["settings.notifySoundDesc"],
    keywords: [
      "notification",
      "sound",
      "beep",
      "audio",
      "alert",
      "notify",
      "通知声音",
      "提示音",
    ],
  },
  {
    id: "general.notifyQuietHours",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-notifyQuietHours",
    labelKey: "settings.notifyQuietHours",
    descKeys: [
      "settings.notifyQuietHoursDesc",
      "settings.notifyQuietHoursStart",
      "settings.notifyQuietHoursEnd",
      "settings.notifyQuietHours.activeNow",
    ],
    keywords: [
      "quiet hours",
      "do not disturb",
      "dnd",
      "notification",
      "desktop",
      "mute",
      "night",
      "免打扰",
      "勿扰",
      "静音时段",
      "桌面通知",
    ],
  },
  {
    id: "general.stopAllSkipConfirm",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-stopAllSkipConfirm",
    labelKey: "settings.stopAllSkipConfirm",
    descKeys: ["settings.stopAllSkipConfirmDesc"],
    keywords: [
      "stop all",
      "skip confirm",
      "busy sessions",
      "tasks",
      "dashboard",
      "no confirm",
      "全部停止",
      "跳过确认",
      "忙碌会话",
    ],
  },
  {
    id: "general.alwaysQuitWithoutAsking",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-alwaysQuitWithoutAsking",
    labelKey: "settings.alwaysQuitWithoutAsking",
    descKeys: ["settings.alwaysQuitWithoutAskingDesc"],
    keywords: [
      "quit",
      "exit",
      "close",
      "busy",
      "confirm",
      "always quit",
      "without asking",
      "退出",
      "结束",
      "忙碌",
      "确认",
      "不再询问",
    ],
  },
  {
    id: "general.openTarget",
    section: "general",
    tab: "app",
    anchorId: "settings-anchor-openTarget",
    labelKey: "settings.openTarget",
    descKeys: [
      "settings.openTargetDesc",
      "settings.openFinder",
      "settings.openTargetEmpty",
      "settings.openTargetPreferredMissing",
    ],
    keywords: ["open in", "finder", "editor", "no editors", "preferred editor"],
  },
];
