import type { SettingsEntry } from "../types";

/** Settings catalog entries — runtime section. */
export const RUNTIME_ENTRIES: readonly SettingsEntry[] = [
  // ── runtime ──
  {
    id: "runtime.privacy",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy",
    labelKey: "settings.privacy",
    descKeys: [
      "settings.privacyDesc",
      "settings.privacy.telemetry",
      "settings.privacy.telemetryDesc",
      "settings.privacy.traceUpload",
      "settings.privacy.traceUploadDesc",
      "settings.privacy.mixpanel",
      "settings.privacy.disableCodebaseUpload",
      "settings.privacy.disableCodebaseUploadDesc",
      "settings.privacy.disableWorkspaceTeleport",
      "settings.privacy.codingData",
      "settings.privacy.codingDataDesc",
      "settings.privacy.sharedWarning",
      "settings.privacy.unsetNotOff",
      "settings.privacy.probe.okAllUnset",
      "settings.privacy.apply.softRespawn",
    ],
    keywords: [
      "privacy",
      "privacy center",
      "telemetry",
      "trace upload",
      "codebase upload",
      "disable_codebase_upload",
      "disable_workspace_teleport",
      "trace_upload",
      "mixpanel",
      "mixpanel_enabled",
      "GROK_TELEMETRY",
      "GROK_EXTERNAL_OTEL",
      "OpenTelemetry",
      "OTEL",
      "external otel",
      "/privacy",
      "coding data",
      "training",
      "retention",
      "unset",
      "probe",
      "隐私",
      "遙測",
      "遥测",
      "隐私中心",
      "隱私",
      "未设置",
      "未設定",
    ],
  },
  {
    id: "runtime.privacy.telemetry",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-telemetry",
    labelKey: "settings.privacy.telemetry",
    descKeys: [
      "settings.privacy.telemetryDesc",
      "settings.privacy.default.telemetry",
      "settings.privacy.unsetNotOff",
    ],
    keywords: [
      "telemetry",
      "features telemetry",
      "product analytics",
      "GROK_TELEMETRY_ENABLED",
      "unset",
    ],
  },
  {
    id: "runtime.privacy.traceUpload",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-traceUpload",
    labelKey: "settings.privacy.traceUpload",
    descKeys: [
      "settings.privacy.traceUploadDesc",
      "settings.privacy.default.traceUpload",
    ],
    keywords: [
      "trace_upload",
      "session trace",
      "trace upload",
      "GROK_TELEMETRY_TRACE_UPLOAD",
    ],
  },
  {
    id: "runtime.privacy.mixpanel",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-mixpanel",
    labelKey: "settings.privacy.mixpanel",
    descKeys: [
      "settings.privacy.mixpanelDesc",
      "settings.privacy.default.mixpanel",
    ],
    keywords: [
      "mixpanel",
      "mixpanel_enabled",
      "GROK_TELEMETRY_MIXPANEL_ENABLED",
      "product analytics",
    ],
  },
  {
    id: "runtime.privacy.codebaseUpload",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-codebaseUpload",
    labelKey: "settings.privacy.disableCodebaseUpload",
    descKeys: [
      "settings.privacy.disableCodebaseUploadDesc",
      "settings.privacy.default.disableCodebaseUpload",
    ],
    keywords: [
      "disable_codebase_upload",
      "codebase upload",
      "upload codebase",
      "index upload",
      "harness",
    ],
  },
  {
    id: "runtime.privacy.workspaceTeleport",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-workspaceTeleport",
    labelKey: "settings.privacy.disableWorkspaceTeleport",
    descKeys: [
      "settings.privacy.disableWorkspaceTeleportDesc",
      "settings.privacy.default.disableWorkspaceTeleport",
    ],
    keywords: [
      "disable_workspace_teleport",
      "workspace teleport",
      "teleport",
      "harness",
    ],
  },
  {
    id: "runtime.privacy.codingData",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-codingData",
    labelKey: "settings.privacy.codingData",
    descKeys: [
      "settings.privacy.codingDataDesc",
      "settings.privacy.codingDataHint",
    ],
    keywords: [
      "/privacy",
      "coding data",
      "training",
      "retention",
      "ZDR",
      "opt out",
    ],
  },
  {
    id: "runtime.privacy.externalOtel",
    section: "runtime",
    tab: "privacy",
    anchorId: "settings-anchor-privacy-externalOtel",
    labelKey: "settings.privacy.externalOtel",
    descKeys: [
      "settings.privacy.externalOtelDesc",
      "settings.privacy.externalOtel.dualOptIn",
      "settings.privacy.externalOtel.unknownNotOff",
      "settings.privacy.externalOtel.contentFree",
      "settings.privacy.externalOtel.noSecrets",
    ],
    keywords: [
      "external otel",
      "OpenTelemetry",
      "OTEL",
      "GROK_EXTERNAL_OTEL",
      "OTEL_METRICS_EXPORTER",
      "OTEL_LOGS_EXPORTER",
      "OTEL_EXPORTER_OTLP_ENDPOINT",
      "OTEL_EXPORTER_OTLP_HEADERS",
      "otel_enabled",
      "dual opt-in",
      "content-free",
      "OTLP",
      "collector",
      "enterprise telemetry",
      "外部 OTEL",
      "开放遥测",
      "開放遙測",
    ],
  },
  {
    id: "runtime.cliPath",
    section: "runtime",
    tab: "cli",
    anchorId: "settings-anchor-cliPath",
    labelKey: "settings.cliPath",
    descKeys: ["settings.cliPathDesc"],
    keywords: ["cli", "binary", "grok path", "path"],
  },
  {
    id: "runtime.platformTip",
    section: "runtime",
    tab: "cli",
    anchorId: "settings-anchor-platform",
    labelKey: "settings.runtime.platformTip",
    descKeys: ["settings.runtime.platformTipDesc"],
    keywords: [
      "platform",
      "os",
      "windows",
      "macos",
      "linux",
      "day-use",
      "dayuse",
      "checklist",
    ],
  },
  {
    id: "runtime.allowUnverifiedCli",
    section: "runtime",
    tab: "cli",
    anchorId: "settings-anchor-allowUnverifiedCli",
    labelKey: "settings.allowUnverifiedCli",
    descKeys: ["settings.allowUnverifiedCliDesc"],
    keywords: ["checksum", "sha256", "unverified", "cli install", "trust"],
  },
  {
    id: "runtime.cliWorktreeDb",
    section: "runtime",
    tab: "cli",
    anchorId: "settings-anchor-cliWorktreeDb",
    labelKey: "settings.cliWorktreeDb.title",
    descKeys: [
      "settings.cliWorktreeDb.desc",
      "settings.cliWorktreeDb.path",
      "settings.cliWorktreeDb.stats",
      "settings.cliWorktreeDb.rebuild",
      "settings.cliWorktreeDb.rebuildDesc",
    ],
    keywords: [
      "worktree db",
      "worktrees.db",
      "cli worktree",
      "db rebuild",
      "db stats",
      "db path",
      "grok worktree db",
      "0.2.117",
      "worktree index",
      "worktree 数据库",
      "worktree 資料庫",
      "重建",
    ],
  },
  {
    id: "runtime.cliUpdate",
    section: "runtime",
    tab: "cli",
    anchorId: "settings-anchor-cliUpdate",
    labelKey: "settings.cliUpdate",
    descKeys: [
      "settings.cliUpdateDesc",
      "settings.cliChannel.switchHint",
      "settings.cliChannel.pinHint",
    ],
    keywords: [
      "cli update",
      "grok update",
      "channel",
      "alpha",
      "stable",
      "version pin",
      "0.2.117",
    ],
  },
  {
    id: "runtime.proxy",
    section: "runtime",
    tab: "network",
    anchorId: "settings-anchor-proxy",
    labelKey: "settings.proxyMode",
    descKeys: [
      "settings.proxyModeDesc",
      "settings.proxyUrl",
      "settings.proxyUrlDesc",
      "settings.proxyNoProxy",
      "settings.proxyNoProxyDesc",
      "settings.proxyRestartHint",
      "settings.proxy.apply.saved",
      "settings.proxy.apply.appHttp",
      "settings.proxy.apply.newAgents",
      "settings.proxy.apply.reconnect",
      "settings.proxy.apply.probeEffective",
      "settings.proxy.apply.manualInvalidInherit",
      "settings.proxyUrlError.empty",
      "settings.proxyUrlError.missingScheme",
      "settings.netProbe",
      "settings.netProbeDesc",
      "settings.netProbeHonesty",
      "settings.netProbeRetry",
      "settings.netProbe.outcome.allOk",
      "settings.netProbe.outcome.partial",
      "settings.netProbe.outcome.allFail",
      "settings.netProbe.empty.hostOnly",
      "settings.netProbe.empty.idle",
      "settings.netProbe.empty.noTargets",
      "settings.netProbe.empty.error",
    ],
    keywords: [
      "proxy",
      "network",
      "HTTP_PROXY",
      "HTTPS_PROXY",
      "ALL_PROXY",
      "NO_PROXY",
      "socks5",
      "socks5h",
      "system proxy",
      "manual proxy",
      "direct",
      "no proxy",
      "connectivity",
      "net probe",
      "network probe",
      "bypass",
      "代理",
      "網路",
      "网络",
      "直連",
      "直连",
      "連通",
      "连通",
      "socks",
      "system",
      "manual",
    ],
  },
  {
    id: "runtime.acp",
    section: "runtime",
    tab: "connection",
    anchorId: "settings-anchor-acpServer",
    labelKey: "settings.acpServer",
    descKeys: [
      "settings.acpServerDesc",
      "settings.acpServerModeHelp",
      "settings.acpServerLocalHint",
      "settings.acpServerServeLink",
      "settings.acpTest",
      "settings.acpProbeOk",
      "settings.acpProbeFail",
    ],
    keywords: [
      "acp",
      "remote agent",
      "host port",
      "tcp",
      "api mode",
      "probe",
      "test connection",
      "health",
      "latency",
      "ws://",
      "host:port",
      "local cli",
      "agent serve",
      "连通",
      "连通性",
      "测试连接",
      "健康检查",
      "API 模式",
      "本机 CLI",
      "本機 CLI",
      "遠端",
      "远程",
    ],
  },
  {
    id: "runtime.leaderServe",
    section: "runtime",
    tab: "connection",
    anchorId: "settings-anchor-leaderServe",
    labelKey: "settings.leader.title",
    descKeys: [
      "settings.leader.desc",
      "settings.leader.start",
      "settings.leader.stop",
      "settings.leader.socket",
      "settings.leader.fleetTitle",
      "settings.leader.fleetDesc",
      "settings.leader.info",
      "settings.leader.honesty.useLeaderNotRunning",
      "settings.leader.err.socketStale",
      "settings.useLeader",
      "settings.serve.title",
      "settings.serve.desc",
      "settings.serve.start",
      "settings.serve.stop",
      "settings.serve.bind",
      "settings.serve.secret",
      "settings.serve.remote",
      "settings.serve.connectionTemplate",
    ],
    keywords: [
      "leader",
      "agent leader",
      "leader.sock",
      "shared backend",
      "socket",
      "leader list",
      "leader info",
      "leader kill",
      "fleet",
      "stale socket",
      "soft-fail",
      "use leader",
      "reachable",
      "websocket",
      "2419",
      "server-key",
      "bind",
      "secret",
      "remote",
      "--remote",
      "proxy",
      "共享后端",
      "共用後端",
      "套接字",
      "陈旧",
      "陳舊",
      "监听",
      "密鑰",
      "密钥",
      "详情",
      "詳情",
    ],
  },
  {
    id: "runtime.agentServe",
    section: "runtime",
    tab: "connection",
    anchorId: "settings-anchor-agentServe",
    labelKey: "settings.serve.title",
    descKeys: [
      "settings.serve.desc",
      "settings.serve.start",
      "settings.serve.stop",
      "settings.serve.bind",
      "settings.serve.secret",
      "settings.serve.remote",
      "settings.serve.connectionTemplate",
      "settings.serve.copyUrl",
      "settings.serve.copyCli",
      "settings.serve.healthNote",
      "settings.sdkConnect.title",
      "settings.sdkConnect.desc",
    ],
    keywords: [
      "serve",
      "agent serve",
      "websocket",
      "ws",
      "2419",
      "bind",
      "secret",
      "server-key",
      "connection url",
      "connection string",
      "--remote",
      "remote",
      "proxy",
      "ACP server",
      "sdk",
      "curl",
      "websocat",
      "remote serve",
      "tcp health",
      "远程",
      "遠端",
    ],
  },
  {
    id: "runtime.sdkConnect",
    section: "runtime",
    tab: "connection",
    anchorId: "settings-anchor-sdkConnect",
    labelKey: "settings.sdkConnect.title",
    descKeys: [
      "settings.sdkConnect.desc",
      "settings.sdkConnect.step1",
      "settings.sdkConnect.step2",
      "settings.sdkConnect.step3",
      "settings.sdkConnect.step4",
      "settings.sdkConnect.step5",
      "settings.serve.start",
      "settings.serve.secret",
    ],
    keywords: [
      "sdk connect",
      "sdk",
      "external client",
      "agent serve",
      "websocket",
      "curl",
      "websocat",
      "probe",
      "tcp",
      "server-key",
      "remote url",
      "外接",
      "探针",
      "探針",
    ],
  },
  {
    id: "runtime.maxConcurrent",
    section: "runtime",
    tab: "pool",
    anchorId: "settings-anchor-maxConcurrentAgents",
    labelKey: "settings.maxConcurrentAgents",
    descKeys: ["settings.maxConcurrentAgentsDesc"],
    keywords: ["concurrent", "pool", "parallel agents"],
  },
  {
    id: "runtime.processBudget",
    section: "runtime",
    tab: "pool",
    anchorId: "settings-anchor-processBudget",
    labelKey: "processBudget.title",
    descKeys: [
      "processBudget.lead",
      "processBudget.plan.headroom",
      "processBudget.plan.atCapBusy",
      "processBudget.plan.empty",
      "processBudget.limit.noneBody",
    ],
    keywords: [
      "process budget",
      "occupancy",
      "warm agents",
      "parked",
      "background",
      "process limit",
      "PROCESS_LIMIT",
      "reclaim",
      "slot",
      "empty pool",
      "empty honesty",
      "并发",
      "並發",
      "进程池",
      "行程池",
      "占用",
      "佔用",
      "回收",
      "闲置",
      "閒置",
      "空池",
    ],
  },
  {
    id: "runtime.idle",
    section: "runtime",
    tab: "pool",
    anchorId: "settings-anchor-agentIdleMinutes",
    labelKey: "settings.agentIdleMinutes",
    descKeys: ["settings.agentIdleMinutesDesc"],
    keywords: ["idle", "recycle"],
  },
  {
    id: "runtime.stall",
    section: "runtime",
    tab: "pool",
    anchorId: "settings-anchor-streamStallSeconds",
    labelKey: "settings.streamStallSeconds",
    descKeys: ["settings.streamStallSecondsDesc"],
    keywords: ["stall", "timeout", "stream"],
  },
  {
    id: "runtime.includePartialMessages",
    section: "runtime",
    tab: "pool",
    anchorId: "settings-anchor-includePartialMessages",
    labelKey: "settings.includePartialMessages",
    descKeys: [
      "settings.includePartialMessagesDesc",
      "settings.includePartialMessages.active",
      "settings.includePartialMessages.softOmit",
      "settings.includePartialMessages.idleOff",
      "settings.includePartialMessages.hostOnly",
      "settings.includePartialMessages.err.cliTooOld",
      "settings.includePartialMessages.err.unknownFlag",
      "settings.includePartialMessages.err.unsupportedFormat",
      "settings.includePartialMessages.err.hostOnly",
      "settings.includePartialMessages.err.other",
    ],
    keywords: [
      "partial stream",
      "include-partial-messages",
      "stream_event",
      "streaming-messages-json",
      "partial messages",
      "headless stream",
      "soft-omit",
      "soft omit",
      "apply path",
      "增量流",
      "部分流式",
      "partial",
    ],
  },
  {
    id: "runtime.workflows",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-workflows",
    labelKey: "settings.workflows",
    descKeys: [
      "settings.workflowsDesc",
      "settings.workflowsHonesty",
      "settings.workflows.runHonesty",
      "settings.workflows.authorHint",
      "settings.workflows.openDocs",
      "settings.workflows.discovered",
      "settings.workflows.noneFound",
      "settings.workflows.run.smoke",
      "settings.workflows.run.launch",
      "settings.workflows.create",
      "settings.workflows.history",
      "settings.workflows.history.honesty",
    ],
    keywords: [
      "workflows",
      "workflow",
      "workflows_enabled",
      "rhai",
      "create-workflow",
      "/workflows",
      "/workflow",
      "orchestration",
      "multi-agent pipeline",
      "validate_only",
      "smoke",
      "headless",
      "workflow tool",
      "template",
      "scaffold",
      "recent runs",
      "history",
      "工作流",
      "工作流程",
      "冒烟",
      "冒煙",
      "模板",
      "最近运行",
      "最近執行",
    ],
  },
  {
    id: "runtime.doctor",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-doctor",
    labelKey: "doctor.title",
    descKeys: ["settings.doctorDesc", "settings.runDoctor"],
    keywords: ["doctor", "diagnose"],
  },
  {
    id: "runtime.traces",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-traces",
    labelKey: "session.tracesTitle",
    descKeys: [
      "session.tracesDesc",
      "session.exportTraceLocal",
      "session.exportTraceUpload",
    ],
    keywords: [
      "trace",
      "traces",
      "session trace",
      "grok trace",
      "export history",
      "诊断",
      "追踪",
    ],
  },
  {
    id: "runtime.reliability",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-reliability",
    labelKey: "reliability.title",
    descKeys: [
      "reliability.settingsDesc",
      "reliability.openFromSettings",
      "reliability.audit.title",
      "reliability.audit.lead",
    ],
    keywords: [
      "reliability",
      "observability",
      "busy",
      "stall",
      "error deck",
      "support zip",
      "audit",
      "ledger",
      "tool audit",
      "permission log",
      "审计",
      "帳本",
      "账本",
      "稽核",
    ],
  },
  {
    id: "runtime.auditRetention",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-auditRetention",
    labelKey: "reliability.audit.retention",
    descKeys: [
      "reliability.audit.retentionDesc",
      "reliability.audit.retention.7",
      "reliability.audit.retention.30",
      "reliability.audit.retention.90",
      "reliability.audit.retention.unlimited",
    ],
    keywords: [
      "audit",
      "ledger",
      "retention",
      "prune",
      "tool audit",
      "permission log",
      "7 days",
      "30 days",
      "90 days",
      "unlimited",
      "保留",
      "留存",
      "清理",
      "审计",
      "帳本",
      "账本",
      "稽核",
    ],
  },
  {
    id: "runtime.batchAgents",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-batch-agents",
    labelKey: "batchAgents.title",
    descKeys: [
      "batchAgents.settingsDesc",
      "batchAgents.openFromSettings",
      "batchAgents.hint",
    ],
    keywords: [
      "batch",
      "batch agents",
      "multi project",
      "multi-project",
      "dispatch",
      "fan out",
      "headless summary",
      "same prompt",
      "批量",
      "多项目",
      "派发",
    ],
  },
  {
    id: "runtime.costRollup",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-cost-rollup",
    labelKey: "costRollup.title",
    descKeys: [
      "costRollup.settingsDesc",
      "costRollup.disclaimer",
      "costRollup.exportCopy",
      "costRollup.clearFilters",
      "costRollup.clear",
    ],
    keywords: [
      "cost",
      "rollup",
      "token usage",
      "estimate",
      "billing",
      "project cost",
      "session cost",
      "export summary",
      "filter",
      "clear samples",
      "费用",
      "费用汇总",
      "用量",
      "token",
      "会话费用",
      "筛选",
      "清除样本",
      "匯出",
      "篩選",
    ],
  },
  {
    id: "runtime.streamingMessagesJson",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-smj",
    labelKey: "smj.title",
    descKeys: ["smj.settingsDesc", "smj.lead", "smj.formatHint"],
    keywords: [
      "streaming-messages-json",
      "streaming messages",
      "ndjson",
      "output-format",
      "anthropic messages",
      "tool_use",
      "headless probe",
      "0.2.117",
      "流式消息",
      "消息 JSON",
    ],
  },
  {
    id: "runtime.streamAcpNdjson",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-stream-acp-ndjson",
    labelKey: "streamAcpNdjson.title",
    descKeys: [
      "streamAcpNdjson.settingsDesc",
      "streamAcpNdjson.lead",
    ],
    keywords: [
      "streaming-json",
      "streaming-messages-json",
      "ndjson",
      "acp",
      "session/update",
      "headless probe",
      "diagnostics",
      "0.2.117",
      "output-format",
      "诊断",
      "流式",
    ],
  },
  {
    id: "runtime.inspect",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-inspect",
    labelKey: "inspect.title",
    descKeys: ["inspect.desc"],
    keywords: ["inspect", "project inspect"],
  },
  {
    id: "runtime.prHub",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-prHub",
    labelKey: "prHub.title",
    descKeys: ["prHub.desc"],
    keywords: [
      "pull request",
      "pull requests",
      "PR",
      "PRs",
      "gh pr",
      "github pr",
      "checks",
      "comments",
      "reviews",
      "conversation",
      "mergeable",
      "CI",
      "PR hub",
      "拉取请求",
      "拉取請求",
      "合并",
      "合併",
      "评论",
      "評論",
      "检查",
      "檢查",
    ],
  },
  {
    id: "runtime.managedSetup",
    section: "runtime",
    tab: "tools",
    anchorId: "settings-anchor-managedSetup",
    labelKey: "managedSetup.title",
    descKeys: [
      "managedSetup.desc",
      "managedSetup.authHint",
      "managedSetup.statusTitle",
      "managedSetup.sigHint",
      "managedSetup.sig.cardTitle",
      "managedSetup.recovery.presentUnverified",
    ],
    keywords: [
      "managed setup",
      "grok setup",
      "managed_config",
      "managed config",
      "deployment key",
      "GROK_DEPLOYMENT_KEY",
      "signature",
      "signature verified",
      "present unverified",
      "presence only",
      "managed_config.sig",
      "requirements.toml",
      "verify_ok",
      "托管",
      "託管",
      "部署密钥",
      "部署金鑰",
      "签名",
      "簽名",
      "验签",
      "驗簽",
      "仅存在性",
      "僅存在性",
    ],
  },
];
